export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#fadae9",
        "outline": "#8d928d",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#0e1f15",
        "surface-container-low": "#1a1c1a",
        "on-background": "#e2e3df",
        "surface-tint": "#ebbac6",
        "tertiary-fixed-dim": "#ddbecd",
        "tertiary": "#ddbecd",
        "surface": "#121412",
        "inverse-surface": "#e2e3df",
        "on-surface": "#e2e3df",
        "on-primary-container": "#c698a4",
        "primary-fixed-dim": "#ebbac6",
        "primary-container": "#52303a",
        "on-secondary-container": "#a7baab",
        "on-tertiary-fixed": "#281620",
        "surface-dim": "#121412",
        "on-primary-fixed-variant": "#603d47",
        "primary-fixed": "#ffd9e2",
        "secondary": "#b8cbbc",
        "error-container": "#93000a",
        "secondary-fixed": "#d4e7d8",
        "on-error-container": "#ffdad6",
        "on-primary": "#472731",
        "outline-variant": "#434844",
        "on-tertiary-container": "#b99caa",
        "inverse-primary": "#7a545e",
        "surface-bright": "#383a37",
        "tertiary-container": "#49343f",
        "surface-container-highest": "#333533",
        "secondary-fixed-dim": "#b8cbbc",
        "on-secondary-fixed-variant": "#394b3f",
        "surface-variant": "#333533",
        "surface-container-high": "#282a28",
        "surface-container-lowest": "#0d0f0d",
        "on-primary-fixed": "#2f121c",
        "primary": "#ebbac6",
        "on-surface-variant": "#c3c8c2",
        "secondary-container": "#394b3f",
        "surface-container": "#1e201e",
        "on-secondary": "#233429",
        "background": "#121412",
        "on-tertiary": "#3f2a35",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#56404c",
        "inverse-on-surface": "#2f312f"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
